version: '2'

services:

  apache-osclass:
    image: r0mdau/stretch-apache2-php7
    environment:
      - VIRTUAL_HOST=osclass.dev
    volumes:
      - ./:/srv/osclass
      - ./osclass.dev.conf:/etc/apache2/sites-enabled/osclass.dev.conf
    links:
      - database
    network_mode: "bridge"

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    network_mode: "bridge"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
    links:
      - database:db
    network_mode: "bridge"